"""create body_metrics table

Revision ID: c84ddce7993f
Revises: 7037d8b50ccb
Create Date: 2026-09-15 11:46:38.534973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c84ddce7993f'
down_revision: Union[str, Sequence[str], None] = '7037d8b50ccb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('body_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('weight', 'resting_hr', 'sleep_hours', 'mobility', name='metrickind'), nullable=False),
    sa.Column('value', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_body_metrics_user_id'), 'body_metrics', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_body_metrics_user_id'), table_name='body_metrics')
    op.drop_table('body_metrics')
    # ### end Alembic commands ###
